[project]
name = "mythwar-site"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-awesome-nav>=3.2.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-macros-plugin>=1.4.0",
    "mkdocs-material>=9.6.20",
]
